#Below you can list the permissions you would like to add when a player uses /bypass
#Use %player% for username of player
#DO NOT REMOVE THE BYPASS.ACTIVE PERMISSION; You can change the command to suit your permission plugin!
#Note: You must negate the permission 'bypass.active' for Admins if they have '*' permission
permissions:
 - lp user %player% permission set bypass.active server=world
 - pex user %player% add bypass.active
 #This is where you take away the permissions on logout or type /bypass again
removepermissions:
 - lp user %player% permission unset bypass.active server=sb
 - pex user %player% remove bypass.active